# Generated by Django 6.1.1 on 2026-09-10 00:44

from django.db import migrations
from django.utils import timezone


def backfill_email_verified_at(apps, schema_editor):
    """Accounts created before email verification existed were never asked
    to verify — retroactively requiring it would lock them out of their
    own accounts. Grandfather them in; only new registrations from here on
    go through the real flow."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email_verified_at__isnull=True).update(email_verified_at=timezone.now())


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.RunPython(backfill_email_verified_at, noop_reverse),
    ]
