# Generated by Django 6.1.1 on 2026-09-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodExchangeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('kcal_per_exchange', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'food exchange categories',
                'db_table': 'food_exchange_categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FoodExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('local_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('ep_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('household_measure', models.CharField(blank=True, max_length=100, null=True)),
                ('is_high_sodium', models.BooleanField(default=False)),
                ('is_high_potassium', models.BooleanField(default=False)),
                ('is_high_phosphorus', models.BooleanField(default=False)),
                ('is_high_fiber', models.BooleanField(default=False)),
                ('is_low_gi', models.BooleanField(default=False)),
                ('ok_for_diabetes', models.BooleanField(default=True)),
                ('ok_for_hypertension', models.BooleanField(default=True)),
                ('ok_for_renal', models.BooleanField(default=True)),
                ('is_free_food', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.foodexchangecategory')),
            ],
            options={
                'db_table': 'food_exchange_items',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('renal', 'Renal'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('general', 'General')], default='general', max_length=20)),
                ('target_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_vegetable', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_fruit', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_milk', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_rice', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_meat', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_fat', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_sugar', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='scheduling.rndclientrelationship')),
            ],
            options={
                'db_table': 'meal_plans',
            },
        ),
        migrations.CreateModel(
            name='MealPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('am_snack', 'AM Snack'), ('lunch', 'Lunch'), ('pm_snack', 'PM Snack'), ('dinner', 'Dinner'), ('bedtime_snack', 'Bedtime Snack')], max_length=20)),
                ('vegetable_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fruit_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('milk_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('rice_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('meat_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fat_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sugar_exchanges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('meal_notes', models.TextField(blank=True, null=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.mealplan')),
            ],
            options={
                'db_table': 'meal_plan_meals',
            },
        ),
        migrations.CreateModel(
            name='MealPlanFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('fel', 'FNRI Food Exchange List'), ('fnri_fct', 'FNRI Food Composition Table'), ('usda', 'USDA FoodData Central'), ('custom', 'Custom')], default='fel', max_length=20)),
                ('external_food_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exchanges', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('household_measure', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nutrition.foodexchangeitem')),
                ('meal_plan_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition.mealplanmeal')),
            ],
            options={
                'db_table': 'meal_plan_food_items',
            },
        ),
    ]
