# Generated by Django 6.1.1 on 2026-09-27 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_mealplan_target_carb_g_mealplan_target_fat_g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('status', models.CharField(choices=[('followed', 'Followed Plan'), ('partially_followed', 'Partially Followed'), ('not_followed', 'Did Not Follow')], max_length=20)),
                ('time_logged', models.TimeField(blank=True, null=True)),
                ('reason_notes', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
                ('meal_plan_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='nutrition.mealplanmeal')),
            ],
            options={
                'db_table': 'meal_logs',
                'constraints': [models.UniqueConstraint(fields=('meal_plan_meal', 'log_date'), name='unique_meal_log_per_day')],
            },
        ),
    ]
