# Generated by Django 6.1.1 on 2026-09-04 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NcpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lab_notes', models.TextField(blank=True, null=True)),
                ('assessment_notes', models.TextField(blank=True, null=True)),
                ('pes_problem', models.CharField(blank=True, max_length=500, null=True)),
                ('pes_etiology', models.TextField(blank=True, null=True)),
                ('pes_signs', models.TextField(blank=True, null=True)),
                ('diet_prescription', models.TextField(blank=True, null=True)),
                ('target_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('target_protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_carb_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('intervention_notes', models.TextField(blank=True, null=True)),
                ('monitoring_notes', models.TextField(blank=True, null=True)),
                ('goal_status', models.CharField(blank=True, choices=[('met', 'Met'), ('partially_met', 'Partially Met'), ('not_met', 'Not Met'), ('ongoing', 'Ongoing')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncp_records', to='scheduling.appointment')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncp_records', to='scheduling.rndclientrelationship')),
            ],
            options={
                'db_table': 'ncp_records',
            },
        ),
        migrations.CreateModel(
            name='PreConsultationScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=50, null=True)),
                ('bmr_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tdee_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extra_active', 'Extra Active')], default='sedentary', max_length=20)),
                ('nrs_score', models.SmallIntegerField(blank=True, null=True)),
                ('nrs_risk', models.CharField(blank=True, choices=[('no_risk', 'No Risk'), ('at_risk', 'At Risk'), ('high_risk', 'High Risk')], max_length=20, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='scheduling.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_consultation_screenings',
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('adherence_pct', models.SmallIntegerField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('rnd_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='scheduling.rndclientrelationship')),
            ],
            options={
                'db_table': 'progress_records',
            },
        ),
    ]
