# Generated by Django 6.1.1 on 2026-09-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressrecord',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
