# Generated by Django 6.1.1 on 2026-09-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_progressrecord_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncprecord',
            name='assessment_extra',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ncprecord',
            name='intervention_extra',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
