# Generated by Django 6.1.1 on 2026-09-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_amt', models.DecimalField(decimal_places=2, default=0, help_text='Frozen at creation — do not recompute from commission_pct after the fact.', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('payment_gateway', models.CharField(blank=True, choices=[('paymongo', 'PayMongo'), ('stripe', 'Stripe'), ('xendit', 'Xendit'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('manual', 'Manual')], max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card'), ('gcash', 'GCash'), ('maya', 'Maya'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20, null=True)),
                ('gateway_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='scheduling.appointment')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='scheduling.rndclientrelationship')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('payout', 'Payout'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('gateway_payload', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.invoice')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
    ]
