# Generated by Django 6.1.1 on 2026-09-04 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('in_person', 'In Person'), ('video', 'Video'), ('chat', 'Chat')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('duration_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('video_session_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_provider', models.CharField(choices=[('zoom', 'Zoom'), ('daily_co', 'Daily.co'), ('jitsi', 'Jitsi'), ('twilio_video', 'Twilio Video'), ('google_meet', 'Google Meet'), ('other', 'Other')], default='daily_co', max_length=20)),
                ('external_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('host_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('participant_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('recording_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('session_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('session_started_at', models.DateTimeField(blank=True, null=True)),
                ('session_ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_min', models.SmallIntegerField(blank=True, null=True)),
                ('provider_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sessions', to='scheduling.appointment')),
            ],
            options={
                'db_table': 'consultation_sessions',
            },
        ),
        migrations.CreateModel(
            name='RndClientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('discharged', 'Discharged')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnd_relationships', to=settings.AUTH_USER_MODEL)),
                ('rnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rnd_client_relationships',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduling.rndclientrelationship'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(help_text='Scale 1-5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='scheduling.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('rnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='rndclientrelationship',
            constraint=models.UniqueConstraint(fields=('rnd', 'client'), name='unique_rnd_client_pair'),
        ),
    ]
