# Generated by Django 6.1.1 on 2026-09-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsession',
            name='video_provider',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('daily_co', 'Daily.co'), ('jitsi', 'Jitsi'), ('twilio_video', 'Twilio Video'), ('google_meet', 'Google Meet'), ('other', 'Other')], default='jitsi', max_length=20),
        ),
    ]
