# Generated by Django 6.1.1 on 2026-09-27 21:56

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rndprofile',
            name='consultation_modes',
            field=models.JSONField(default=profiles.models.default_consultation_modes, help_text='Subset of video/chat/in_person'),
        ),
    ]
