# Generated by Django 6.1.1 on 2026-09-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rndprofile_consultation_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rndprofile',
            name='prc_license_image',
            field=models.CharField(blank=True, help_text='Cloudinary public_id of an authenticated (non-public) upload', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rndprofile',
            name='prc_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
